# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sage back Prod CI

on:
  push:
    branches: [ prod ]
  pull_request:
    branches: [ prod ]

jobs:
  deploy:
  
    runs-on: ubuntu-latest

    steps:
    - name: SSH deploy backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST_BIAPI }}
        username: ${{ secrets.SSH_USERNAME_BIAPI }}
        key: ${{ secrets.SSH_KEY_BIAPI }}
        port: ${{ secrets.SSH_PORT_BIAPI }}
        script: |
          cd /home/sage_prod/sage_backend
          git pull origin prod
          docker-compose up -d --force-recreate --no-deps --build  sage_back
